### ISSUE TITLE
Research Potential Database Services

### ISSUE THREAD

**Issue by alejmedinajr** [alejmedinajr/AI-Detector#12]

**Comment by Caleb-Highsmith** [comment]
Things that need to be considered:
* Potential Costs
* Is the DB relational or non-relational
* How simple is the UI for interacting with the database (is it hosted on a site)

**Comment by alejmedinajr** [comment]
@Caleb-Highsmith When I was doing research associated with #10, I found something called [Postgresql](https://www.postgresql.org/). You might want to check it out, it could be a good option since it integrates well with the backend frameworks I was looking into. Django also has built in database functionalities: [look here](https://docs.djangoproject.com/en/5.0/topics/db/queries/). At the same time, these were just things I came across while looking into the frontend stuff. Just think it would help!

**Comment by Caleb-Highsmith** [comment]
Added research notes to shared google drive folder.

**Comment by Caleb-Highsmith** [comment]
Closing ticket because research notes on this is now int the shared drive
