### ISSUE TITLE
Develop Python RESTful API 

### ISSUE THREAD

**Issue by Caleb-Highsmith** [alejmedinajr/AI-Detector#16]
Now that we have a list of frameworks to choose from, we need to determine how a Python API is going to integrate with a Javascript web app.

**Comment by Caleb-Highsmith** [comment]
Starting ticket, researching Python RESTful API's using flask

**Comment by alejmedinajr** [comment]
Meeting notes with @Caleb-Highsmith can be found in the Google Drive (contains start time and meeting notes)

**Comment by Caleb-Highsmith** [comment]
Created initial API and have it displayed on Swagger UI. Still trying to create an endpoint for chatGPT responses.

**Comment by Caleb-Highsmith** [comment]
Created API endpoint for chatGPT response and successfully returned the response on Swagger's UI. See screenshot on meeting notes.

**Comment by Caleb-Highsmith** [comment]
Closing ticket because API is now built. See meeting notes in shared drive. Also generating more tickets to create new API endpoints for different integrations
