### ISSUE TITLE
Research different API endpoints that we can add

### ISSUE THREAD

**Issue by Caleb-Highsmith** [alejmedinajr/AI-Detector#20]
Now that we have a chatGPT integration, it makes sense to see if we can add more AI services to our RESTful API.

**Comment by Caleb-Highsmith** [comment]
First option that makes the most sense is Bard. Currently researching what is required from their own API

**Comment by Caleb-Highsmith** [comment]
This is a good article that breaks it down. I will be compiling notes on this in the shared drive. 

[](https://docs.kanaries.net/articles/google-bard-api)

**Comment by alejmedinajr** [comment]
It might also be interesting to look into AI tools for specific domains, such as the [Ghostwriter] API (https://www.ghostwriter.wiki/features/graphql-api). This is just one example, but I am sure there are specific tools for domains/areas. It might also be interesting to look into other type of media/assignments besides text, like the AI tools that produce slideshows.

**Comment by Caleb-Highsmith** [comment]
@alejmedinajr I think to start we can target the LLM and then start adding in ones that that can scan images and interpret if that makes sense. Hope that helps!

**Comment by alejmedinajr** [comment]
@Caleb-Highsmith I was talking more about something like [this](https://tome.app/), where you can provide a prompt about what your presentation is about, and it creates the presentation for you. I am sure there are other ones out there, but it would be interesting to consider having assignment types, then having a different page for different assignments (i.e. presentation, paper, code, etc). For something like the presentation, we could just show what the presentation would look like via pdf or pptx. We would need to find an api for one of these tools. For this app called tome, a user can describe what their presentation needs to have (i.e. assignment instructions), and the ai tool creates the presentation with content.
<img width="1512" alt="Screenshot 2024-02-10 at 1 24 16 PM" src="https://github.com/alejmedinajr/AI-Detector/assets/100097809/d779adc7-3390-47f6-b2f8-9edd862bb764">
 
I do agree that we should focus first on just generative text models, but this would be cool to also include if we have time.

**Comment by Caleb-Highsmith** [comment]
@alejmedinajr Just got around to looking at this. This is a great idea and I really like the concept of this. I think once we get a base going with the LLMs then we can transition to more premium features like this one. Things like this will probably separate our AI detection from ones that already exists.

**Comment by Caleb-Highsmith** [comment]
Just an update on this issue. This is an ongoing thread for continued conversation on more endpoints.

**Comment by TjRaffert** [comment]
When experimenting with Bard I realized that Bard provides links to its sources which is interesting for later on if we want to mess with that.

**Comment by alejmedinajr** [comment]
Closing this issue, no longer current with the state of our project.
