### ISSUE TITLE
Connect Bard/Gemini Endpoint to React front end

### ISSUE THREAD

**Issue by Caleb-Highsmith** [alejmedinajr/AI-Detector#27]
Now that we have the endpoint created for Gemini/bard, we need to connect it to the React app. There is already existing code that integrates the chatGPT so most of the code should be boiler plate (meaning already existing if you haven't heard of this term before). Contact @alejmedinajr  if you have questions on how to integrate.

Note: See the[ New Ticket Tutorial](https://docs.google.com/document/d/1G4-NT2rf5iLNYoyn6YLObq-fDk7oxEdgzmU-e9XxleE/edit) on how to make a new branch and what not.

**Comment by Caleb-Highsmith** [comment]
@alejmedinajr Can you add more direction on how to get started with this? Like which JS file to look in etc.

**Comment by alejmedinajr** [comment]
There is a folder called `main-react-app`, this contains a folder called `src`. Inside this folder is a file called `PromptForm.js`. This is the main file responsible for creating the form the user currently can see when the app is running. It also has the connection to the FastAPI where it makes use of the function for the api.  
<img width="615" alt="Screenshot 2024-02-17 at 12 02 57 PM" src="https://github.com/alejmedinajr/AI-Detector/assets/100097809/6f1fe630-c7c9-4a51-8fa0-c77433cf207a">

This image (also in `PromptForm.js`) shows how to make the connection to the FastAPI. Later on today, I will update the documentation in this file so it is easier to follow. For now, just know the connection is made by calling the same name of the function that matches the code responsible for using the chatgpt api. If you look in `API.py`, you will see the relationship between the two. To add a new endpoint, you will need to do something similar in `PromptForm.js`, but for gemini. This will mean that a new Post function needs to be made in `API.py`. Just use the example of the post function used for the chatgpt api as a starting point.

**Comment by alejmedinajr** [comment]
Update: I created a new documentation branch that should only be used for adding documentation or cleaning up unused code. There is a merge request now for the documentation branch that has been added to `PromptForm.js` that should help improve understanding of the code.

**Comment by TjRaffert** [comment]
I spent 30 minutes setting up my desktop with all relevant applications for our project. This includes Github desktop VS code. I also read through the New Ticket Procedure.

**Comment by TjRaffert** [comment]
I followed al the steps to get the code up on my desktop with the proper branch. I am reading through the instructions left by @alejmedinajr and @Caleb-Highsmith on what is required for this ticket.

**Comment by TjRaffert** [comment]
I have spent 45 minutes trying to restructure the code to accept multiple endpoints in the most concise way possible. This is my first time working with JavaScript besides the tutorial so I am still getting the hang of it.

**Comment by TjRaffert** [comment]
In the last 30 minutes I think I made a working solution but I am working on a branch that was created before the bard endpoint was merged by @Caleb-Highsmith. I am trying to figure out what the proper way to resolve this issue is.

**Comment by TjRaffert** [comment]
I spent another 30 minutes just making a new branch with up to date code. It took me a while to understand @Caleb-Highsmith updates to API.py.

**Comment by TjRaffert** [comment]
I have spent the last 30 minutes downloading and figuring out Nodejs I am the only one on the team using windows so the instructions don't really apply.

**Comment by TjRaffert** [comment]
I was able get the website up and running I think some of my changes stopped it from fetching the results properly. I am going to make a drop down menu for selecting which LLM.

**Comment by TjRaffert** [comment]
I made a drop down menu for selecting the LLM but it still isn't showing the results properly. I am going to make a response showcase so we can more easily see what is happening.

**Comment by TjRaffert** [comment]
I added a response text box that will be useful later on for testing and trouble shooting. I realized I didn't have FastAPI running so that is why my backend wasn't working.

**Comment by TjRaffert** [comment]
I am still struggling with the FastAPI so I will ask the group about it tomorrow.

**Comment by TjRaffert** [comment]
I spent 45 minutes getting getting fastapi working and made a pull request for someone to look at.
