### ISSUE TITLE
Login Page [frontend]

### ISSUE THREAD

**Issue by alejmedinajr** [alejmedinajr/AI-Detector#30]
There needs to be a login page created for users to use. For this ticket, only focus on the front end part of this (i.e. creating the login page that the user will see on the react app).

**Comment by noahzamarripa** [comment]
Properly Designing the app on Figma,, Figma has useful design features and integrations so ill be updating the design in the shared folder

**Comment by noahzamarripa** [comment]
Added button places for information about app, create account, login,,, adding functionality

**Comment by noahzamarripa** [comment]
designing page after a user logs in,, where user would put assignment directions, upload work, choose AI model

**Comment by noahzamarripa** [comment]
Added those places for the user,, going to make components of the AI model button for response when one is chosen

**Comment by noahzamarripa** [comment]
the button will now turn green when a model is selected,, updated the page slightly with better directions for the user on what to do

**Comment by Caleb-Highsmith** [comment]
Posting this here just in case you need. Here is a website that has HTML and CSS templates for login pages. Feel free to use this for inspiration or to get a general HTML structure going or don't use it all. Up to you! 

https://colorlib.com/wp/html5-and-css3-login-forms/

**Comment by noahzamarripa** [comment]
working on this now

**Comment by noahzamarripa** [comment]
created the component folder and am putting the login page into it,, created login jsx and css file

**Comment by noahzamarripa** [comment]
ran into small problem trying to open react app but resolved,, changing code around to display login from instead of prompt form for now

**Comment by noahzamarripa** [comment]
now showing correct page,, got basic text title up and username/password boxes as well

**Comment by noahzamarripa** [comment]
added useState hooks to the username and password email,, doing the same with create account page

**Comment by noahzamarripa** [comment]
watched https://www.youtube.com/watch?v=Y-XW9m8qOis&t=919s and https://www.youtube.com/watch?v=kghwFYOJiNg&t=51s for help,, have not coded since last

**Comment by noahzamarripa** [comment]
button on LoginForm is not appearing on the page and im getting an error when trying to create logic for going between this page and account page

**Comment by noahzamarripa** [comment]
getting closer,, can get to account page but not back to login
