### ISSUE TITLE
Login/Signup Page [backend]

### ISSUE THREAD

**Issue by alejmedinajr** [alejmedinajr/AI-Detector#31]
This ticket focuses on the backend of the login/signup page. It should be started once the front end part is complete (see issue #30. 
Things that need to be done:

1. Regex check for the actual content sent by the user (make sure it is valid based on how we define password and username)
2. A user should be inserted into the database only if the user is successful in creating an account (this step obviously has other sub tasks that need to be done analogous to it)

**Comment by noahzamarripa** [comment]
Starting on this now

**Comment by noahzamarripa** [comment]
We switched to firebase for database instead of Postgre and am reading the ways google has authentication. I am thinking that we are going to need to build a custom auth service

**Comment by noahzamarripa** [comment]
watching and reading the documentation for authentication on firebase. https://www.youtube.com/watch?v=rbuSx1yEgV8&t=24s,, https://www.youtube.com/watch?v=rQvOAnNvcNQ

**Comment by noahzamarripa** [comment]
Created a branch for this issue to code up firebase authentication,, installed SDK and imported firebase to our project and added our specific firebase configuration

**Comment by noahzamarripa** [comment]
imported authentication library,, working on what to take as sign in parameters(email, username, password)

**Comment by noahzamarripa** [comment]
Found out we need an upgrade to the firebase account to set up our own server in order to have custom tokens for user account authentication,, using the email/password is what we will do,, committed changes about firebase connection

**Comment by noahzamarripa** [comment]
Allowed email and password authentication for our app in the firebase settings,, creating a password based account

**Comment by noahzamarripa** [comment]
working on sign in password code and will save the other sign up authentication in the other ticket

**Comment by noahzamarripa** [comment]
still working on this,, putting code in index.js for logging in and still need to get that information connected to a button inside LoginForm.jsx

**Comment by noahzamarripa** [comment]
changed the firebase configuration to a separate file in order to clean up im changing how im setting this up because before was a bit more tedious

**Comment by noahzamarripa** [comment]
figuring out the jsx version of what I needed and am now putting logic on handleSubmit function to take in login

**Comment by noahzamarripa** [comment]
working on auth

**Comment by noahzamarripa** [comment]
changed the login page to have the email and password in a single object rather than handling separate use states. also changed the ticket to handle both login and signups. also changed how button click to signup/login handle the new object

**Comment by noahzamarripa** [comment]
created the functions to handle login and signup when clicking the corresponding button,, need the UI to change when this happens(it will sign in and remain on the page as if nothing happened),, errors are being thrown by firebase if a user enters an invalid email/password when signing up or logging in but no UI feedback for this,, will add error messages soon

**Comment by TjRaffert** [comment]
I am starting to work on this to see if I can add anything aesthetically after the pull request is accepted.

**Comment by TjRaffert** [comment]
I have spent 30 minutes trying to get this branch up and running but I am getting a lot of errors. Download the React DevTools for a better development experience: https://reactjs.org/link/react-devtools
LoginForm.jsx:53 Uncaught ReferenceError: handleSubmit is not defined
    at LoginForm (LoginForm.jsx:53:1)
    at renderWithHooks (react-dom.development.js:16305:1)
    at mountIndeterminateComponent (react-dom.development.js:20074:1)
    at beginWork (react-dom.development.js:21587:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at beginWork$1 (react-dom.development.js:27451:1)
    at performUnitOfWork (react-dom.development.js:26557:1)
    at workLoopSync (react-dom.development.js:26466:1)
LoginForm @ LoginForm.jsx:53
renderWithHooks @ react-dom.development.js:16305
mountIndeterminateComponent @ react-dom.development.js:20074
beginWork @ react-dom.development.js:21587
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27451
performUnitOfWork @ react-dom.development.js:26557
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
performConcurrentWorkOnRoot @ react-dom.development.js:25738
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
Show 14 more frames
Show less
LoginForm.jsx:53 Uncaught ReferenceError: handleSubmit is not defined
    at LoginForm (LoginForm.jsx:53:1)
    at renderWithHooks (react-dom.development.js:16305:1)
    at mountIndeterminateComponent (react-dom.development.js:20074:1)
    at beginWork (react-dom.development.js:21587:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at beginWork$1 (react-dom.development.js:27451:1)
    at performUnitOfWork (react-dom.development.js:26557:1)
    at workLoopSync (react-dom.development.js:26466:1)
LoginForm @ LoginForm.jsx:53
renderWithHooks @ react-dom.development.js:16305
mountIndeterminateComponent @ react-dom.development.js:20074
beginWork @ react-dom.development.js:21587
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27451
performUnitOfWork @ react-dom.development.js:26557
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
recoverFromConcurrentError @ react-dom.development.js:25850
performConcurrentWorkOnRoot @ react-dom.development.js:25750
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
Show 15 more frames
Show less
react-dom.development.js:18687 The above error occurred in the <LoginForm> component:

    at LoginForm (http://localhost:3000/static/js/bundle.js:597:96)
    at div
    at div
    at http://localhost:3000/static/js/bundle.js:1859:66
    at ChakraComponent (http://localhost:3000/static/js/bundle.js:77664:76)
    at http://localhost:3000/static/js/bundle.js:74727:5
    at VStack
    at div
    at http://localhost:3000/static/js/bundle.js:1859:66
    at ChakraComponent (http://localhost:3000/static/js/bundle.js:77664:76)
    at App (http://localhost:3000/static/js/bundle.js:53:74)
    at EnvironmentProvider (http://localhost:3000/static/js/bundle.js:75191:5)
    at ColorModeProvider (http://localhost:3000/static/js/bundle.js:73425:5)
    at ThemeProvider (http://localhost:3000/static/js/bundle.js:1911:50)
    at ThemeProvider (http://localhost:3000/static/js/bundle.js:77893:5)
    at ChakraProvider (http://localhost:3000/static/js/bundle.js:75046:5)
    at ChakraProvider2 (http://localhost:3000/static/js/bundle.js:75458:5)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js:18687
update.callback @ react-dom.development.js:18720
callCallback @ react-dom.development.js:13923
commitUpdateQueue @ react-dom.development.js:13944
commitLayoutEffectOnFiber @ react-dom.development.js:23391
commitLayoutMountEffects_complete @ react-dom.development.js:24688
commitLayoutEffects_begin @ react-dom.development.js:24674
commitLayoutEffects @ react-dom.development.js:24612
commitRootImpl @ react-dom.development.js:26823
commitRoot @ react-dom.development.js:26682
finishConcurrentRender @ react-dom.development.js:25892
performConcurrentWorkOnRoot @ react-dom.development.js:25809
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
Show 15 more frames
Show less
LoginForm.jsx:53 Uncaught ReferenceError: handleSubmit is not defined
    at LoginForm (LoginForm.jsx:53:1)
    at renderWithHooks (react-dom.development.js:16305:1)
    at mountIndeterminateComponent (react-dom.development.js:20074:1)
    at beginWork (react-dom.development.js:21587:1)
    at beginWork$1 (react-dom.development.js:27426:1)
    at performUnitOfWork (react-dom.development.js:26557:1)
    at workLoopSync (react-dom.development.js:26466:1)
    at renderRootSync (react-dom.development.js:26434:1)
    at recoverFromConcurrentError (react-dom.development.js:25850:1)
    at performConcurrentWorkOnRoot (react-dom.development.js:25750:1)
LoginForm @ LoginForm.jsx:53
renderWithHooks @ react-dom.development.js:16305
mountIndeterminateComponent @ react-dom.development.js:20074
beginWork @ react-dom.development.js:21587
beginWork$1 @ react-dom.development.js:27426
performUnitOfWork @ react-dom.development.js:26557
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
recoverFromConcurrentError @ react-dom.development.js:25850
performConcurrentWorkOnRoot @ react-dom.development.js:25750
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
Show 12 more frames
Show less

**Comment by TjRaffert** [comment]
I spent another 30 minutes debugging the error. Me and Caleb are now looking at it together.

**Comment by TjRaffert** [comment]
Me and Caleb worked on this for an hour and couldn't figure it out we tried reinstalling various things and looking at Noah's version history. We decided we will look at it tomorrow as a group.

**Comment by noahzamarripa** [comment]
moved the firebase config to separate folder to fix imports ,, fixing the issues

**Comment by noahzamarripa** [comment]
progress on fixing the handling user credentials,, continuing

**Comment by noahzamarripa** [comment]
took out the lines in index.js that were not needed,, chakraUI is having issues

**Comment by noahzamarripa** [comment]
still issues with not being able to find variables and app.js 'cant resolve 'chakra-UI...' '

**Comment by noahzamarripa** [comment]
im changing up how the useState is used and changing functions to update each field in the login and account form

**Comment by noahzamarripa** [comment]
cleared up most of the errors now the only one remaining are the 'cant resolve' ones
