### ISSUE TITLE
User Account Page [frontend]

### ISSUE THREAD

**Issue by alejmedinajr** [alejmedinajr/AI-Detector#32]
There needs to be a page created for the user account information. This needs to contain information such as name, username, an option to change password (don't worry about backend for this, it is in another ticket), and any other information related to the user.

**Comment by noahzamarripa** [comment]
created the buttons and navigation to this page,, working on it now\

**Comment by noahzamarripa** [comment]
most of the page has information on it to fill in in order to create an account,, added a button to back to Home Screen in order to login with newly created account,, added forgot password button needs functionality,, still need to figure out how someone is an admin

**Comment by noahzamarripa** [comment]
added checkbox for student or instructor(might change how the type of account is determined later),, skeleton done for now,, will go to login page design issue#30

**Comment by noahzamarripa** [comment]
Have been working on account page but also creating this file and basic skeleton page as well for working out functionality,, will elaborate more now at the time of this message

**Comment by noahzamarripa** [comment]
this page now shows up with basic information and two buttons: Back to Login and Create Account,, functionality going back to login is not working,, create account will need a separate kind of functionality(connecting with database)

**Comment by noahzamarripa** [comment]
fixed the functionality of going back and forth between the two pages,, began some styling on it, basic css,, still also need to add more fields for account creation and still need to add functionality
