### ISSUE TITLE
User Account Page [backend]

### ISSUE THREAD

**Issue by alejmedinajr** [alejmedinajr/AI-Detector#33]
This ticket is for the backend functionality of the user account page. This includes things like making the actual connection to the database and making the update queries (again using the password validation functionality). There should also be discussion for an option to delete an account.

**Comment by noahzamarripa** [comment]
Added the button and navigation to this page,, creating this page right now

**Comment by noahzamarripa** [comment]
this issue was combines with issue 31 where the database will update with an account added,, pull request for the issue was made just a few minutes ago

**Comment by noahzamarripa** [comment]
closing this to make new issues for further features regarding singing up/logging in
