### ISSUE TITLE
File Upload Feature 

### ISSUE THREAD

**Issue by alejmedinajr** [alejmedinajr/AI-Detector#37]
This ticket is dedicated to implementing the front end and back end of a file upload feature. This means the user should see a button that allows them to click it and upload a file. The file then needs to be saved or somehow stored/sent to the backend so that it can be parsed. Ignore any functionality related to parsing for now, that will be a later issue. Instead, the goal of this ticket is to create a file upload button on the react app main page that allows the user to upload a file. [Here](https://youtu.be/iM4Pz-9oyiE?si=VM4qFYpgTpLW1bsq) is a good video source to start that shows how you can do this using the tools for this project (react and fastAPI). I do not think we want to save the files like the video does, but it is still a good start regardless.

**Comment by Caleb-Highsmith** [comment]
Starting the ticket by first watching the video for context.

**Comment by Caleb-Highsmith** [comment]
Finished up video. Stopping ticket for now.

**Comment by Caleb-Highsmith** [comment]
Starting the ticket again. Got a new laptop so I am downloading dependencies and whatnot

**Comment by Caleb-Highsmith** [comment]
Just got all dependencies and react tools installed. Moving onto database stuff

**Comment by Caleb-Highsmith** [comment]
Finished up new React component and front end side of the ticket. Aesthetics need to change eventually but this will do for now. Moving onto to FastAPI/Backend side of the ticket to handle db update on file upload.

**Comment by Caleb-Highsmith** [comment]
Got the backend complete. The current logic is that we are saving the uploaded files into our local project under a folder called uploads. We can easily manipulate this logic to allow for database updates but the file upload functionality is there. Putting in a PR for this.

**Comment by alejmedinajr** [comment]
Starting on this now so that I can add an additional submission area for a submission file.

**Comment by alejmedinajr** [comment]
Update: I started with the regular text because I thought this would be easier. I basically put everything related to submission into a box and added another text area. Doing this makes me think I can add two toggle buttons to move from text to file making it easier to use the features. I also centered the box containing everything so it looks more visually pleasing. The other buttons need to be rearranged, but this can be done later. 
<img width="805" alt="Screenshot 2024-04-07 at 4 24 37 PM" src="https://github.com/alejmedinajr/AI-Detector/assets/100097809/53ec57eb-dfc2-4bf1-9c6e-b380da68584e">

**Comment by alejmedinajr** [comment]
Update: I changed the form again so now either the instructions or submission can be a file upload or text (using the toggle button). I think this will be easier for the users to use. I also moved the submit prompt button to a lower placement and the chatgpt and gemini/bard buttons to a lower level that make sense visually (or at least I think so). I think it would look better if I use one of those standard visual boxes for the file upload area that is the same as the text (that way it doesnt look weird like right now).

<img width="735" alt="Screenshot 2024-04-07 at 4 57 26 PM" src="https://github.com/alejmedinajr/AI-Detector/assets/100097809/48136f96-86b4-4c3c-bff5-2ade55152107">

**Comment by alejmedinajr** [comment]
Current update:  I am still working on merging the functionality of api calls since now these can be via file or text (which means the api call needs to change as well. The troubling part is finding a good way of integrating both existing portions, but I am pretty close I feel like.

**Comment by alejmedinajr** [comment]
Current Update: I tried to alter the API.py file to account for file submission in the same function, but this ended up being harder than I expected, so my next approach that I am close to testing involves parsing the files from the react side, which may end up being faster since itll send that text.

**Comment by alejmedinajr** [comment]
Update: Still working on file parsing on react

**Comment by alejmedinajr** [comment]
Update: I forgot to add an update, but I was working for the past hour on trying to parse text from a file immediately. I initially tried to parse it on submit, but instead, I am trying to find a way to parse a file on change that way the same variable can be used.

**Comment by alejmedinajr** [comment]
Update: I made some progress where now the parsed content comes to console, but then it is not able to read the text. It is strange why this happens, but this is definitely a step forward. I think I know how to fix this problem.

**Comment by alejmedinajr** [comment]
Update: I am at a new stopping point where I rearranged the buttons. I was not able to resolve the parsing issue, so I will ask @Caleb-Highsmith for assistance (or we may decide to just use the existing functionality, losing the ability to mix and match between text and file input). The image is the new layout for the main page, and I think it looks nicer. Maybe something to consider is only showing the gpt and gemini toggle buttons when the response is ready...

<img width="1512" alt="Screenshot 2024-04-07 at 8 46 59 PM" src="https://github.com/alejmedinajr/AI-Detector/assets/100097809/8bfc2348-6cfc-4c9f-8ee1-10d093998546">

**Comment by alejmedinajr** [comment]
Closing this issue since the file form has been condensed into a single form that the user can mix and match between text or file content.
