### ISSUE TITLE
Create Labeled Training Data

### ISSUE THREAD

**Issue by alejmedinajr** [alejmedinajr/AI-Detector#43]
If we are to create a machine learning model that will be used to determine the probability and possibility that a student's submission features content from AI tools, we need training data. This training data also needs to be labeled to reflect whether the specific instance did use AI tools for submission. The purpose of this would be to train a model that can be used for new data. Currently, there are three text comparison functions that also need to be tested further. Having this dataset will allow us to further assess the accuracy of our text comparison functions.

**Comment by TjRaffert** [comment]
I have started working on this issue.

**Comment by TjRaffert** [comment]
I have spent 45 minutes planning out what problems I am going to use and checking if I can find enough man made solutions. I have made a document to hold our training data and organize it. I am going to get 10 AI and Human solutions for an easy, medium and hard problem. I have decided on using merging two sorted lists in python as our easy problem.

**Comment by TjRaffert** [comment]
I spent 35 minute's copying python solutions into the doc and documenting them.

**Comment by TjRaffert** [comment]
I have spent 30 minutes working on the AI generated results. I ran into this this summer it doesn't like when you try and generate data in bulk and it kind of stops itself.

**Comment by TjRaffert** [comment]
I have spent another 45 minutes generating data. I have also realized looking at the code that when we make the machine learning model we will have to take into account the different amounts of boiler plate code.

**Comment by TjRaffert** [comment]
I have been working on this for 20 minutes. I gathered all the data for easy two sorted lists. I decided on using Longest substring Without repeating characters as the medium problem.

**Comment by TjRaffert** [comment]
Worked another 25 minutes grinding out the data set finished human solutions for Medium.

**Comment by TjRaffert** [comment]
https://docs.google.com/document/d/1Q37zbWanvRYZ4zXbvTXvEyOdMzbtSw4LJbZq1XGRmL0/edit Spent 15 minutes finishing up the AI solutions for medium

**Comment by TjRaffert** [comment]
I have spent 30 minutes making a folder on a new branch that will hold all our training. I also made the individual files and organized them in a structured way.

**Comment by alejmedinajr** [comment]
@TjRaffert Which branch is this on? I would like to start using them for the text comparison methods I have created to see how they perform.

**Comment by TjRaffert** [comment]
I am working on putting all the training data code in individual pdf files like we discussed in class.

**Comment by TjRaffert** [comment]
I spent 30 minutes making all 20 pdf files and am currently filling them in with the proper data.

**Comment by TjRaffert** [comment]
I spent 35 minutes adding all the code for the easy problem

**Comment by TjRaffert** [comment]
I spent 45 minutes finishing up the folder and changing a couple data points.
