### ISSUE TITLE
Make all font sizes bigger on Prompt Page

### ISSUE THREAD

**Issue by Caleb-Highsmith** [alejmedinajr/AI-Detector#50]
Update all font sizes on the prompt page to be bigger.

**Comment by TjRaffert** [comment]
I have been trying to work on this for 45 minutes but I was getting a lot of errors. I got rid of the errors when compiling but the page is blank. I am going to restart my machine so magic might happen.

**Comment by TjRaffert** [comment]
I have spent another 45 minutes debugging. Now for some reason my github desktop is full of node modules and I am unsure what to do with them.

**Comment by TjRaffert** [comment]
I have started working on this again.

**Comment by TjRaffert** [comment]
I have spent another 45 minutes experimenting with the text sizes. Font sizes are good but I am trying to move the textarea prompt box to take up more room.

**Comment by TjRaffert** [comment]
I spent another 30 minutes I found a way to make the text box width of the screen but it doesn't look great so I am trying to add a border.

**Comment by TjRaffert** [comment]
I was able to add a border that looks good. I am now moving on to the AI toggle buttons.

**Comment by TjRaffert** [comment]
I worked another 30 minutes I was able to get everything centered and looking good I am going to work on making a pull request.

**Comment by TjRaffert** [comment]
I have spent 30 minutes looking into this lock file error that isn't letting me push my code.

**Comment by TjRaffert** [comment]
I spent another 40 minutes working on this I think I deleted something on accident while the environment was running and it didn't like it.

**Comment by TjRaffert** [comment]
import React, { useState } from 'react';
import { Button, Textarea, VStack, ButtonGroup, Heading, Box } from "@chakra-ui/react";

function PromptForm() {
    const [prompt, setPrompt] = useState("");
    const [response, setResponse] = useState("");
    const [selectedButton, setSelectedButton] = useState(null);

    const handleSubmit = async (event) => {
        event.preventDefault();
        // Add your fetch logic here
    };

    const handleButtonClick = (buttonName) => {
        setSelectedButton(prevButtonName => 
            prevButtonName === buttonName ? null : buttonName
        );
    };

    return (
        <Box width="100%" p={5} maxWidth="960px" margin="auto"> {/* Centering the form and adding padding */}
            <Heading marginBottom={5} size="xl" textAlign="center">Enter your prompt</Heading>

            <form onSubmit={handleSubmit}>
                <VStack spacing={5} align="stretch">
                    <Textarea
                        value={prompt}
                        onChange={(e) => setPrompt(e.target.value)}
                        placeholder="Enter your prompt here..."
                        borderColor="blue.500"
                        borderWidth="2px"
                        borderRadius="lg"
                        p={5}
                        resize="vertical"
                        fontSize="lg"
                        height="160px"
                        _hover={{ borderColor: "blue.600" }}
                        _focus={{ boxShadow: "0 0 0 2px blue.300" }}
                    />
                    <Button type="submit" colorScheme="blue" size="lg" width="full" _hover={{ bg: "blue.600" }}>
                        Submit Prompt
                    </Button>
                </VStack>
            </form>

            {response && (
                <Box mt={5}>
                    <Heading as="h2" size="md" marginBottom={2}>Response:</Heading>
                    <Textarea
                        readOnly
                        value={response}
                        width="100%"
                        minHeight="200px"
                        fontSize="lg"
                        borderColor="blue.500"
                        borderWidth="2px"
                        _hover={{ borderColor: "blue.600" }}
                        _focus={{ boxShadow: "0 0 0 2px blue.300" }}
                    />
                </Box>
            )}

            <ButtonGroup spacing={4} mt={5} width="100%" justifyContent="center">
                <Button
                    onClick={() => handleButtonClick("ChatGPT")}
                    colorScheme={selectedButton === "ChatGPT" ? "blue" : "gray"}
                    size="lg"
                    _hover={{ bg: "blue.600", color: "white" }}
                >
                    ChatGPT
                </Button>
                <Button
                    onClick={() => handleButtonClick("GeminiBard")}
                    colorScheme={selectedButton === "GeminiBard" ? "blue" : "gray"}
                    size="lg"
                    _hover={{ bg: "blue.600", color: "white" }}
                >
                    Gemini/Bard
                </Button>
            </ButtonGroup>
        </Box>
    );
}

export default PromptForm;

**Comment by TjRaffert** [comment]
I worked for another 20 minutes to get it pushed but isn't working. I will try it on another machine tomorrow.

**Comment by TjRaffert** [comment]
I have started working on getting the lock issue resolved.

**Comment by TjRaffert** [comment]
Making a pull request

**Comment by TjRaffert** [comment]
I spent 30 minutes doing that
