### ISSUE TITLE
Make Database Tables

### ISSUE THREAD

**Issue by TjRaffert** [alejmedinajr/AI-Detector#52]

**Comment by TjRaffert** [comment]
https://www.google.com/search?sca_esv=26a7465d6347b026&rlz=1C1VDKB_enUS1082US1082&q=firebase+realtime+database&tbm=vid&source=lnms&sa=X&sqi=2&ved=2ahUKEwiWyoyC-emEAxV0_skDHecCBFAQ0pQJegQIDxAB&biw=1920&bih=919&dpr=1#fpstate=ive&vld=cid:5abfaadb,vid:dx_gkSb-Ch0,st:0 I spent 20 minutes watching this tutorial so I could see how to make the tables properly

**Comment by TjRaffert** [comment]
I spent 30 minutes working on these tables. I think Alejandro had already made a practice faculty one I am updating it with the fields we talked about in class Wednesday.

**Comment by TjRaffert** [comment]
I have spent another 30 minutes creating the tables from class. I am not 100% sure if I am doing it right but I am going to examine it after I finish the tables.

**Comment by TjRaffert** [comment]
I spent another 30 minutes finishing up the tables I am going to try and check if they are connected properly.

**Comment by Caleb-Highsmith** [comment]
Closing issue. Tables have been created.
