### ISSUE TITLE
Programing Language selection to add to the prompts

### ISSUE THREAD

**Issue by TjRaffert** [alejmedinajr/AI-Detector#57]
If we add a programing language selection it will help the model not have to interpret which programing language was used. Right now it just gets the programing language based off of the blank document which works but doesn't seem super clean.

**Comment by alejmedinajr** [comment]
This is not something we should prioritize prior to code freeze. Although, see issue #73 which deals with file parsing for programming languages (also something that should be left for the end). We could append the programming language based on the extension if we do get around to that issue. I am going to close this as not intended so we can prioritize other more important issues.
