### ISSUE TITLE
Add form submissions to the user account page

### ISSUE THREAD

**Issue by TjRaffert** [alejmedinajr/AI-Detector#63]

**Comment by TjRaffert** [comment]
I am working on this now

**Comment by TjRaffert** [comment]
I have worked for 40 minutes I made a branch and am getting it running. I am also making a document for getting the site up and running.

**Comment by TjRaffert** [comment]
I have started working on this issue.

**Comment by TjRaffert** [comment]
I have been getting the code up and running for 30 minutes I am missing various downloads and imports.

**Comment by TjRaffert** [comment]
I worked another 30 minutes working through errors with Noah. I was able to get the frontend up and working but the backend connection isn't so I am working on that.

**Comment by TjRaffert** [comment]
I spent another 30 minutes trying to get the backend working and it just isn't. Noah is running into similar problems on his end.

**Comment by TjRaffert** [comment]
I worked another 45 minutes I re installed the firebase packages. I also re statred everything and still it isn't working. This is challenging because there isn't an error message it just isn't working.

**Comment by TjRaffert** [comment]
I worked another 30 minutes I have no idea why but I manually went into the database and created a user and was able to login with the credentials.

**Comment by TjRaffert** [comment]
I worked another 45 minutes I am working on adding the form submissions to the user account page.

**Comment by TjRaffert** [comment]
I worked another 30 minutes I am figuring out the format I am going to store the the past submissions.

**Comment by TjRaffert** [comment]
I worked another 40 minutes I setup some front end stuff for this but I need to discus with the group tomorrow  about the database.

**Comment by alejmedinajr** [comment]
I went ahead and implemented this and it is now on main (codefreeze is pretty close). Closing the issue now.
