### ISSUE TITLE
Mixed File Mode on Prompt Page

### ISSUE THREAD

**Issue by alejmedinajr** [alejmedinajr/AI-Detector#66]
Currently, the upload file feature and text feature on the prompt page are in the same area. The text works, but the upload file (either both upload file or mixed mode) do not work. One potential way to go about this is to parse from react, and send that string to the FastAPI. Other ways might also be possible...

**Comment by Caleb-Highsmith** [comment]
Starting ticket now

**Comment by Caleb-Highsmith** [comment]
Still working on this. I had to restructure some of the API. Hopinh to get a working call soon.

**Comment by Caleb-Highsmith** [comment]
Taking a break on this.

**Comment by alejmedinajr** [comment]
I just fixed this, now mixed file/text mode works. A user can upload a file and send text. The parsing is just happening on the react app before it is sent to the FastAPI.
