### ISSUE TITLE
Report Page

### ISSUE THREAD

**Issue by noahzamarripa** [alejmedinajr/AI-Detector#67]
The user(professor accounts) will be able to see a report page that is a table of their past submissions, percentage, and a button to see each comparison functions' accuracy. As well as the ability to say whether or not the comparison was useful (with a yes or no button) to include it in the custom AI model. Issue #62 will be included on this page in the form of modals for each of the comparison functions(see issue #62 for more information on what this will look like).
![IMG_3217](https://github.com/alejmedinajr/AI-Detector/assets/91333145/fab2d334-d456-4559-bf6f-06d6a2b03d38)

**Comment by noahzamarripa** [comment]
Working on this now

**Comment by noahzamarripa** [comment]
Ran into local issues regarding not having some packages installed and the react app was not compiling,, I have installed everything but there is some issue still.

**Comment by noahzamarripa** [comment]
nearly fixed all of the issues,, there is an exporting issue now

**Comment by noahzamarripa** [comment]
solved the exporting issue and can finally work on the issue as intended. There were many installations others did on their machines that were not done on mine as we have all worked on different issues

**Comment by noahzamarripa** [comment]
New error appeared after fixing what was originally the problem,, however this is more unclear on what is happening as it could be a multitude of things.

**Comment by noahzamarripa** [comment]
Created .js file for report page and imported starter imports like chakra and react router stuff,, making the skeleton page now

**Comment by noahzamarripa** [comment]
added function to navigate back to account page and made a bot to organize the information modals about comparison information

**Comment by noahzamarripa** [comment]
Added theme toggle button and imported HStack to line up the modals horizontally. Using text import to put a small title above the modals as in "Comparison Information'

**Comment by noahzamarripa** [comment]
Added the 3 modals next to each other with placeholder explanations,, each has their respective button to open with corresponding title

**Comment by alejmedinajr** [comment]
Update: Am still working on setting up the database so the metrics can be stored for the signed in user (and they will be able to generate their history of reports)

**Comment by alejmedinajr** [comment]
Update: File-File metric comparison works and is stored in firebase, though each report is saved, I need to make it for individual users by adding an extra level (which should be easy in theory). 
![Uploading Screenshot 2024-04-18 at 12.18.44 AM.png…]()

**Comment by alejmedinajr** [comment]
Update: I just realized that this does not matter since I proactively saved the user id in the report as well, I can just order by user id and time to only get the reports from the current user.

**Comment by alejmedinajr** [comment]
Made a basic report page that works, i need to make it match the rest of the app. I also realized that when generating a report, the user needs to also enter an assignment name (or the file name needs to also be saved to the report object).

<img width="1217" alt="Screenshot 2024-04-18 at 1 06 55 AM" src="https://github.com/alejmedinajr/AI-Detector/assets/100097809/d14cd46f-5fe2-4402-9084-0a77e9b8f6d2">

**Comment by alejmedinajr** [comment]
Current Update: New aesthetically pleasing and cleaned up report page, also has navigation to other relevant pages like prompt, account home, and sign out. 

<img width="1217" alt="Screenshot 2024-04-18 at 1 06 55 AM" src="https://github.com/alejmedinajr/AI-Detector/assets/100097809/19579389-aada-4ce0-8d36-4ddfbae3e6a7">

**Comment by alejmedinajr** [comment]
@noahzamarripa I am going to push these changes so that you can incorporate your modal code to the table headers (for the metric explanations).

**Comment by alejmedinajr** [comment]
Update: I hooked up the machine learning model, and I tested it out with one of my papers. I think now it would be fairly simple to add the self training buttons.

<img width="1319" alt="Screenshot 2024-04-18 at 2 40 18 AM" src="https://github.com/alejmedinajr/AI-Detector/assets/100097809/6198159e-38e4-48b2-a2b0-87dc27e00fc3">

**Comment by alejmedinajr** [comment]
Update: Now there is a not complete implementation for self labeling (with the chakra thumbs up or down buttons (they are really icons)). This is hooked up to the api, but it does not do anything to the model yet. The idea is that the user labels the data and the model is training again with this new data. 
 
<img width="1319" alt="Screenshot 2024-04-18 at 3 26 45 AM" src="https://github.com/alejmedinajr/AI-Detector/assets/100097809/9ff71898-91d3-43de-a804-2cb1f64004ed">

**Comment by noahzamarripa** [comment]
Closing this issue as I am incorporating the modals in the up-to-date code in a new issue,, this issue is referenced in the description in the new issue
