### ISSUE TITLE
Forgot my password

### ISSUE THREAD

**Issue by TjRaffert** [alejmedinajr/AI-Detector#69]
There is currently no option for the user to reset their password, which is an essential feature to have on any application/service. Since we are using Firebase and its associated google Auth, there should be an easy way to implement this. I know I have reset my own password from the console, so there should be a defined function that we can do to achieve this.

**Comment by Caleb-Highsmith** [comment]
I forgot to add comment but I worked on this the whole class period and for another hour afterward (Took a break for lunch).

**Comment by Caleb-Highsmith** [comment]
Pretty simple fix once I imported some firebase auth functions. Got the alerts setup properly and tested reset functionality.
