### ISSUE TITLE
Find External Assignments to use for Training

### ISSUE THREAD

**Issue by alejmedinajr** [alejmedinajr/AI-Detector#7]
It would be helpful to have external assignments that can be used for training where the assignments have the following qualities: 

- Unique assignments in that they are not commonly used/easily accessible online 
- Higher level courses
- @anthonybsouthwestern mentioned she could help with this

**Comment by TjRaffert** [comment]
Here is what was said in the email from @anthonybsouthwestern 

The University of Washington has a lot of computer science courses and for the most part the prompts are available from their website in a fairly easy to navigate format. Noticeably it includes the most recent offering and then years of historical offerings for many as well. See https://www.cs.washington.edu/education/courses/

**Comment by TjRaffert** [comment]
We decided to use leetcode problems which works I am going to close this issue.
