### ISSUE TITLE
User Guide Modal

### ISSUE THREAD

**Issue by alejmedinajr** [alejmedinajr/AI-Detector#71]
There should be some "help" or "guide" modal that pops up on the prompt page that tells the user good practices to use for entering prompts. This solves the problem of us being responsible for the quality prompts being sent. At the end of the day, the prompts are only as good as the people sending them (which would be true even if we perform "prompt engineering").

**Comment by noahzamarripa** [comment]
referenced in issue containing the progress for this issue
