### ISSUE TITLE
Add Documentation to Components

### ISSUE THREAD

**Issue by alejmedinajr** [alejmedinajr/AI-Detector#75]
Better/more documentation needs to be added to all of our component files. These are the files contained within the `components` subdirectory of our `snitch-ai` folder. 

The following need documentation:

- `AccountHome.js`
- `AuthenticationForm.jsx`
- `CreateAccountForm.jsx`
- `History.jsx`
- `LoginForm.jsx`
- `PromptForm.js`
- `ThemeToggleButton.js`

Everyone will be assigned to this issue because everyone should add documentation to the code in these files. We can decide to split them up, but this needs to be done.

**Comment by Caleb-Highsmith** [comment]
Starting on this issue now.

**Comment by Caleb-Highsmith** [comment]
Added references. Putting in a PR now.
