### ISSUE TITLE
Update python-code README

### ISSUE THREAD

**Issue by alejmedinajr** [alejmedinajr/AI-Detector#78]
Currently, we do not have a README file for the python-code directory. It needs to have its own README file that has detailed information about the python specific components of the project.

**Comment by alejmedinajr** [comment]
This can be done after presentations (but before the final turn in deadline for final products).

**Comment by TjRaffert** [comment]
I am working on this

**Comment by TjRaffert** [comment]
I have worked 35 minutes filling out this readme.

**Comment by TjRaffert** [comment]
I worked another 25 minutes and finished the readme. I made a pull request.
