### ISSUE TITLE
Update snitch-ai README

### ISSUE THREAD

**Issue by alejmedinajr** [alejmedinajr/AI-Detector#79]
The README file for our react app (located in `snitch-ai`) needs to be updated so it explains about our component files and the react components of our project.

**Comment by Caleb-Highsmith** [comment]
Forgot to add a comment but I have been working on this for the past 30 minutes. Basically just explaining each of our react components that exist in our app.

**Comment by Caleb-Highsmith** [comment]
Should be good to go. I also got rid of some unnecessary files.
