### ISSUE TITLE
High Level Design: Figma

### ISSUE THREAD

**Issue by alejmedinajr** [alejmedinajr/AI-Detector#8]

**Comment by noahzamarripa** [comment]
- file upload button/ area
- basic text input
- login/signup
- instructions file/area and student solution file/area
- CHECK button
- comparison percentage
- figure out student/admin pages
- verify users to anthony

**Comment by noahzamarripa** [comment]
Created login page with button to admin and student frame

**Comment by noahzamarripa** [comment]
Put an admin checkbox that will allow/not allow admin login

**Comment by TjRaffert** [comment]
Can we spend some team time this week to truly figure out what functionality we want to keep? I am planning on doing my own mock up on Figma and I think we need to agree on some functionality as a team together.

**Comment by alejmedinajr** [comment]
@TjRaffert It would be helpful if you start with the functionality/design that @noahzamarripa made and put into the drive. You can also add functionality for a user to edit the information about their account, along with the toggles for different ai tools. Other than that, if you create your own mockup, we can definitely spend time talking about what features to add/remove from there. In general, I would say it is efficient to build on existing mockups so that we can make forward progress!

**Comment by alejmedinajr** [comment]
We are near the end of the semester, so it is highly unlikely we will need to draw a high-level figma design. Although it would be nice to have our very first figma design that @noahzamarripa created featured in our presentation so we can talk about how our design process evolved over the semester. I believe this is located in our shared google drive. Closing this issue now.
