### ISSUE TITLE
User Mode Ability

### ISSUE THREAD

**Issue by alejmedinajr** [alejmedinajr/AI-Detector#81]
If we have time, we should implement the ability to split the mode and features based on the users. There might be an easy way to do this with google Auth. If there is not, this should be something left for the end.

**Comment by Caleb-Highsmith** [comment]
Checking this ticket out. Hopefully, it is not that hard to implement

**Comment by Caleb-Highsmith** [comment]
I don't think this will be too difficult of an issue. I added the role selction on account creation but we are having issues differentiating between using firestore or our realtime database.

**Comment by Caleb-Highsmith** [comment]
Ok so I got the updates to work correctly. Now we are properly storing the professor and student roles in the real time database. I am going to work on adding toggle between the different views. Basically I am going to restrict the views of the student and verify that what they can see.

**Comment by Caleb-Highsmith** [comment]
Ok I think I am actually going to put a PR for this now. I will open a new ticket for restriciting the views in a minute but I also fixed the sign out issue in this ticket. @alejmedinajr
