### ISSUE TITLE
Infinite Spin in Report Page

### ISSUE THREAD

**Issue by alejmedinajr** [alejmedinajr/AI-Detector#86]
There is an infinite spin wheel that occurs when the user refreshes the page from the report page. This should be addressed so that the user is redirected to login, or refreshing the page does not actually log them out. 

<img width="1319" alt="Screenshot 2024-04-19 at 3 27 07 AM" src="https://github.com/alejmedinajr/AI-Detector/assets/100097809/43f639fe-1140-4f1e-8f80-c23f7224c09b">

**Comment by Caleb-Highsmith** [comment]
Picking up ticket now

**Comment by Caleb-Highsmith** [comment]
This ended up being a really easy fix. Just needed to save auth state and prevent default form action when a user is logged in essentially.
