### ISSUE TITLE
Research what type of front-end frameworks/libraries to use

### ISSUE THREAD

**Issue by alejmedinajr** [alejmedinajr/AI-Detector#9]

**Comment by Caleb-Highsmith** [comment]
Some good starting points are:
* ReactJS
* AngularJS
* VueJS

**Comment by TjRaffert** [comment]
I am not sure how much we care about this but is making it mobile friendly important?

**Comment by Caleb-Highsmith** [comment]
Closing ticket since we have react front end built.
